# Generated by Django 5.0.2 on 2024-09-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('game_id', models.CharField(max_length=100)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('game_date', models.DateTimeField()),
                ('score_home', models.IntegerField(blank=True, null=True)),
                ('score_away', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
