# Generated by Django 5.0.2 on 2024-09-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_game_score_away_remove_game_score_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='game',
        ),
        migrations.AddField(
            model_name='score',
            name='game_id',
            field=models.CharField(default='default_game_id', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
