# Generated by Django 5.0.2 on 2024-09-12 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_score_game_score_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateField(),
        ),
    ]
