# Generated by Django 5.0.2 on 2024-09-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_game_game_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_time',
        ),
        migrations.AlterField(
            model_name='game',
            name='game_date',
            field=models.DateTimeField(),
        ),
    ]
