# Generated by Django 5.0.2 on 2024-09-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_game_game_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='nflweek',
            name='last_updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
