# Generated by Django 5.0.2 on 2026-10-01 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_nflweek_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='kickoff',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='schedule_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='scores_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.IntegerField(db_index=True, default=2024),
        ),
        migrations.AddField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'In progress'), ('final', 'Final')], default='scheduled', max_length=10),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
