# Generated by Django 5.0.2 on 2024-09-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatistics',
            name='counted_games',
            field=models.TextField(default=''),
        ),
    ]
