# Generated by Django 5.0.2 on 2026-10-02 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userstatistics_counted_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstatistics',
            name='counted_games',
        ),
    ]
